/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.table.DefaultTableModel;
import mitosv0.RealMachine;

/**
 *
 * @author Tomas
 */
public class RealMachineGUI extends javax.swing.JFrame {

    /**
     * Creates new form RealMachineGUI
     */
    
    RealMachine RM;
    
    //Reikalinga nusakyti lenteles reiksmiu tipui
    TableDataTypes tableDataType = TableDataTypes.Hex;
    public enum TableDataTypes {
        Int,
        Hex,
        Char
    }
    public TableDataTypes getTableDataType(){
        return tableDataType;
    }
    
    public RealMachineGUI(RealMachine RM) {
        super("Real machine");
        initComponents();
        this.RM = RM;
        this.setVisible(true);
        
        updateRegisterFields();  
        updateFlagInfo();
    }
    
        public void updateAll()
    {
        updateRegisterFields();
        updateFlagInfo();
    }
        
    private void updateRegisterFields()
    {
        PLRTextField.setText(Integer.toHexString(RM.PLR.getValue()));
        R1TextField.setText(Integer.toHexString(RM.R1.getValue()));
        R2TextField.setText(Integer.toHexString(RM.R2.getValue()));
        ICTextField.setText(Integer.toHexString(RM.IC.getValue()));
        CTextField.setText(Integer.toHexString(RM.C.getValue()));
        STextField.setText(Integer.toHexString(RM.S.getValue()));
        
        TimerTextField.setText(Integer.toHexString(RM.timer.getValue()));
        MODETextField.setText(modeToString(RM.mode.isSupervisor()));
        PITextField.setText(Integer.toHexString(RM.PI.getValue()));
        SITextField.setText(Integer.toHexString(RM.SI.getValue()));
        CH1TextField.setText(CHStateToString(RM.CH1.isOpen()));
        CH2TextField.setText(CHStateToString(RM.CH2.isOpen()));
        CH3TextField.setText(CHStateToString(RM.CH3.isOpen()));
        CH4TextField.setText(CHStateToString(RM.CH4.isOpen()));
    }
    
    
    private void updateFlagInfo()
    {
        ZFCheckBox.setSelected(RM.C.isZeroFlagSet());
        SFCheckBox.setSelected(RM.C.isSignFlagSet());
        OFCheckBox.setSelected(RM.C.isOverflowFlagSet());
    }
    
    private String CHStateToString(boolean state)
    {
        if (state)
            return new String ("Open");
        else 
            return new String ("Closed");
    }

    private String modeToString(boolean mode)
    {
        if (!mode)
            return new String ("Superv.");
        else 
            return new String ("User");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableDataTypeButtonGroup = new javax.swing.ButtonGroup();
        operationsPanel = new javax.swing.JPanel();
        registerPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PLRTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        R1TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        R2TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ICTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        STextField = new javax.swing.JTextField();
        registerPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TimerTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MODETextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PITextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        SITextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CH1TextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CH2TextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CH3TextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        CH4TextField = new javax.swing.JTextField();
        statusFlagPanel = new javax.swing.JPanel();
        ZFCheckBox = new javax.swing.JCheckBox();
        SFCheckBox = new javax.swing.JCheckBox();
        OFCheckBox = new javax.swing.JCheckBox();
        buttonPanel = new javax.swing.JPanel();
        runButton = new javax.swing.JButton();
        stepButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoryTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tableDataTypeIntegerToggleButton = new javax.swing.JToggleButton();
        tableDataTypeHexToggleButton = new javax.swing.JToggleButton();
        tableDataTypeCharToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        operationsPanel.setLayout(new javax.swing.BoxLayout(operationsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        registerPanel1.setLayout(new java.awt.GridLayout(0, 2, 2, 2));

        jLabel1.setText("PLR");
        registerPanel1.add(jLabel1);
        registerPanel1.add(PLRTextField);

        jLabel2.setText("R1");
        registerPanel1.add(jLabel2);
        registerPanel1.add(R1TextField);

        jLabel3.setText("R2");
        registerPanel1.add(jLabel3);
        registerPanel1.add(R2TextField);

        jLabel4.setText("IC");
        registerPanel1.add(jLabel4);
        registerPanel1.add(ICTextField);

        jLabel5.setText("C");
        registerPanel1.add(jLabel5);
        registerPanel1.add(CTextField);

        jLabel6.setText("S");
        registerPanel1.add(jLabel6);
        registerPanel1.add(STextField);

        operationsPanel.add(registerPanel1);

        registerPanel2.setLayout(new java.awt.GridLayout(0, 2, 2, 2));

        jLabel7.setText("TIMER");
        registerPanel2.add(jLabel7);
        registerPanel2.add(TimerTextField);

        jLabel8.setText("MODE");
        registerPanel2.add(jLabel8);
        registerPanel2.add(MODETextField);

        jLabel9.setText("PI");
        registerPanel2.add(jLabel9);
        registerPanel2.add(PITextField);

        jLabel10.setText("SI");
        registerPanel2.add(jLabel10);
        registerPanel2.add(SITextField);

        jLabel11.setText("CH1");
        registerPanel2.add(jLabel11);
        registerPanel2.add(CH1TextField);

        jLabel12.setText("CH2");
        registerPanel2.add(jLabel12);
        registerPanel2.add(CH2TextField);

        jLabel13.setText("CH3");
        registerPanel2.add(jLabel13);
        registerPanel2.add(CH3TextField);

        jLabel14.setText("CH4");
        registerPanel2.add(jLabel14);
        registerPanel2.add(CH4TextField);

        operationsPanel.add(registerPanel2);

        statusFlagPanel.setLayout(new javax.swing.BoxLayout(statusFlagPanel, javax.swing.BoxLayout.LINE_AXIS));

        ZFCheckBox.setText("ZF");
        statusFlagPanel.add(ZFCheckBox);

        SFCheckBox.setText("SF");
        statusFlagPanel.add(SFCheckBox);

        OFCheckBox.setText("OF");
        statusFlagPanel.add(OFCheckBox);

        operationsPanel.add(statusFlagPanel);

        buttonPanel.setLayout(new java.awt.GridLayout());

        runButton.setText("Run");
        buttonPanel.add(runButton);

        stepButton.setText("Step");
        stepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(stepButton);

        operationsPanel.add(buttonPanel);

        getContentPane().add(operationsPanel);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        memoryTable.setModel(new MemoryTableModel(RM, this));
        memoryTable.setColumnSelectionAllowed(true);
        memoryTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                memoryTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(memoryTable);
        memoryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        tableDataTypeButtonGroup.add(tableDataTypeIntegerToggleButton);
        tableDataTypeIntegerToggleButton.setText("Integer");
        tableDataTypeIntegerToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableDataTypeIntegerToggleButtonActionPerformed(evt);
            }
        });
        jPanel2.add(tableDataTypeIntegerToggleButton);

        tableDataTypeButtonGroup.add(tableDataTypeHexToggleButton);
        tableDataTypeHexToggleButton.setText("Hex");
        tableDataTypeHexToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableDataTypeHexToggleButtonActionPerformed(evt);
            }
        });
        jPanel2.add(tableDataTypeHexToggleButton);

        tableDataTypeButtonGroup.add(tableDataTypeCharToggleButton);
        tableDataTypeCharToggleButton.setText("Char");
        tableDataTypeCharToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableDataTypeCharToggleButtonActionPerformed(evt);
            }
        });
        jPanel2.add(tableDataTypeCharToggleButton);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stepButtonActionPerformed

    private void memoryTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_memoryTableInputMethodTextChanged

    }//GEN-LAST:event_memoryTableInputMethodTextChanged

    private void tableDataTypeIntegerToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableDataTypeIntegerToggleButtonActionPerformed
        tableDataType = TableDataTypes.Int;
        memoryTable.repaint();
    }//GEN-LAST:event_tableDataTypeIntegerToggleButtonActionPerformed

    private void tableDataTypeCharToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableDataTypeCharToggleButtonActionPerformed
        tableDataType = TableDataTypes.Char;
        memoryTable.repaint();
    }//GEN-LAST:event_tableDataTypeCharToggleButtonActionPerformed

    private void tableDataTypeHexToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableDataTypeHexToggleButtonActionPerformed
        tableDataType = TableDataTypes.Hex;
        memoryTable.repaint();
        
    }//GEN-LAST:event_tableDataTypeHexToggleButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CH1TextField;
    private javax.swing.JTextField CH2TextField;
    private javax.swing.JTextField CH3TextField;
    private javax.swing.JTextField CH4TextField;
    private javax.swing.JTextField CTextField;
    private javax.swing.JTextField ICTextField;
    private javax.swing.JTextField MODETextField;
    private javax.swing.JCheckBox OFCheckBox;
    private javax.swing.JTextField PITextField;
    private javax.swing.JTextField PLRTextField;
    private javax.swing.JTextField R1TextField;
    private javax.swing.JTextField R2TextField;
    private javax.swing.JCheckBox SFCheckBox;
    private javax.swing.JTextField SITextField;
    private javax.swing.JTextField STextField;
    private javax.swing.JTextField TimerTextField;
    private javax.swing.JCheckBox ZFCheckBox;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable memoryTable;
    private javax.swing.JPanel operationsPanel;
    private javax.swing.JPanel registerPanel1;
    private javax.swing.JPanel registerPanel2;
    private javax.swing.JButton runButton;
    private javax.swing.JPanel statusFlagPanel;
    private javax.swing.JButton stepButton;
    private javax.swing.ButtonGroup tableDataTypeButtonGroup;
    private javax.swing.JToggleButton tableDataTypeCharToggleButton;
    private javax.swing.JToggleButton tableDataTypeHexToggleButton;
    private javax.swing.JToggleButton tableDataTypeIntegerToggleButton;
    // End of variables declaration//GEN-END:variables
}
